### ISSUE TITLE
Remover angular do código de release

### ISSUE THREAD

**Issue by teles** [teles/frontpress#103]
Atualmente o FrontPress possui 4 dependências:

* Angularjs;
* Ui-router;
* ngDisqus;
* ng-infinite-scroll

Todas essas dependências estão sendo incluídas dentro dos arquivos de release gerados.
Gostaria de remover o angularjs dos releases, pois:

* Diminuiria drasticamente o tamanho dos arquivos minificados (de ~245 para ~75kb);
* Permitiria que o FrontPress seja usado com versões anteriores e legadas do angularjs;
* Deixaria explícita a associação entre o angular e o FrontPress.

Não tenho a intenção de remover as outras dependências do release, pois:

* Obrigar o usuário a fazer `<script src>` para começar a usar o projeto pode causar rejeição;
* Não me parece necessário que a associação entre FrontPress e essas dependências seja tão explícita; 
* Essas dependências não representam um aumento muito grande no tamanho do release final minificado

O que acha, @alisonmonteiro ?

Depois dessa issue para usar o FrontPress será necessário importar o angular + arquivo de release do FrontPress.

**Comment by alisonmonteiro** [comment]
@teles acho uma boa retirar. 

>Diminuiria drasticamente o tamanho dos arquivos minificados (de ~245 para ~75kb);
Permitiria que o FrontPress seja usado com versões anteriores e legadas do angularjs;

Pra mim, estes acima seriam os 2 principais pontos.

Inclusive, acha seria interessante adicionar uma feature na CLI, onde o usuário pode selecionar se deseja incluir o angular e qual a versão? 👀

**Comment by teles** [comment]
Valeu, @alisonmonteiro !
Estou removendo o angular, só tá faltando eu descobrir a origem de um erro aqui rs.
