### ISSUE TITLE
Adicionar jshint

### ISSUE THREAD

**Issue by dineshtrivedi** [teles/frontpress#104]
Essa issue tem como objetivo adicionar o jshint como processo de validação. Além disso, será adicionado um pre-commit hook no git para bloquear commit de arquivos que não passem nessa validação.

**Comment by teles** [comment]
@dineshtrivedi muito obrigado. 
Ficou excelente.

Duas observações:

* Quando o arquivo já existe e a task `pre-commit` é rodada, dá erro. "Error: Destination file exists (.git/hooks/pre-commit) - use force option to replace"
* Seria bom remover dos arquivos analisados pelo pre-commit tudo que estiver dentro do diretório `/release`, pois nele só existem arquivos gerados/concatenados/minificados.

**Comment by dineshtrivedi** [comment]
Boa, @teles 
Corrigi e submeti um novo PR.

**Comment by teles** [comment]
PR merged. Up and running!
Thanks, @dineshtrivedi
