### ISSUE TITLE
Task default do Gulp entra em loop infinito no MacOs

### ISSUE THREAD

**Issue by luizotcarvalho** [teles/frontpress#107]
Ao rodar o gulp ele entra em loop infinito. 

![captura de tela 2017-01-02 as 16 15 34](https://cloud.githubusercontent.com/assets/1590532/21594194/d964f318-d106-11e6-89f1-f854049e23a2.png)

Suspeito que seja causado pelo watch.

**Comment by teles** [comment]
Valeu por observar, @luizotcarvalho ! 
Eu tinha visto isso ocorrer mas não dei a devida atenção.

Quer trabalhar na solução? :)
