### ISSUE TITLE
Publish FrontPress as bower package

### ISSUE THREAD

**Issue by teles** [teles/frontpress#110]
I just started FrontPress development planning that it could be both npm and bower package.
In some moment I realized that dependencies management would be much more easier if I only choose one package manager. See #89 

But now that dependencies are more clear, and releases files are being automatic generated I think we could publish FrontPress as bower package.

I would like users to be able to install FrontPress by doing:

```
bower install frontpress
```

There is no need to manage dependencies in bower. All the necessary files for users are in [release folder](https://github.com/frontpressorg/frontpress/tree/master/release). No need for dependencies to be avaliable for bower.

**Comment by teles** [comment]
@woliveiras take a look if you want  :)

**Comment by woliveiras** [comment]
Maked! #111

**Comment by teles** [comment]
I merged your PR #111, @woliveiras. 
Now users can import FrontPress using: `bower install frontpress`.

Thank you so much
