### ISSUE TITLE
Conjunto de diretivas auxiliares

### ISSUE THREAD

**Issue by teles** [teles/frontpress#23]
Quando um desenvolvedor importar o frontpress e quiser mexer nas views, acho que pode ser interessante que ele encontre uma estrutura pre-definida de diretivas/tags para trabalhar.

**Exemplo de estrutura para a view de trecho de post:**

``` html
<post-date format="dd/mm/yyyy"></post-date>
<post-title has-link="true"></post-title>
<post-content></post-content>
<read-more-link></read-more-link>
```

Assim, o desenvolvedor que quisesse colocar novos itens na página do trecho de post adicionaria/removeria/moveria essas tags.

As perguntas são:
- Isso seria útil para desenvolvedores?
- Se for útil, que tags seriam interessantes serem criadas?

cc @alisonmonteiro  @woliveiras

**Comment by woliveiras** [comment]
Isso seria muito útil, pois fica parecido com as funções que o WordPress nos disponibiliza para criação de templates pelo PHP.

Aqui temos mais funções que podem ser criadas no Angular como diretivas: https://codex.wordpress.org/Function_Reference

**Comment by alisonmonteiro** [comment]
Muito útil! Além disso, poderíamos ter algumas diretivas que já chamariam essas outras que você exemplificou, tipo:

``` html
<simple-post has-thumbnail="true" full-post="false" />
```

O que acham? Complicaria muito?

**Comment by woliveiras** [comment]
Acho interessante também @alisonmonteiro

**Comment by teles** [comment]
Beleza pura, @alisonmonteiro  e @woliveiras. Vou definir as tags a serem criadas para o MVP :)

Definir as tags a serem criadas será o critério de pronto dessa issue.

**Comment by woliveiras** [comment]
Show de bola

**Comment by teles** [comment]
Para validar a ideia vou construir as seguintes tags:

``` html
<post-excerpt>
    <post-title> <!-- h2 com link -->
    <post-date><!-- formato de data definido na configuração do blog -->
    <post-featured-image>
    <post-excerpt-text>
</post-excerpt>


<full-post>
    <post-title> h1 sem link
    <post-date><!-- formato de data definido na configuração do blog -->
    <post-featured-image>
    <post-content>
    <post-tags>
    <post-categories>
    <disqus>
</full-post>
```

Vou tentar fazer isso de uma forma que tags que são usadas na listagem e no post completo sejam a mesma diretiva respondendo a modelos diferentes dependendo da tela em que estão.
