### ISSUE TITLE
Botões de compartilhamento no detalhe de post

### ISSUE THREAD

**Issue by teles** [teles/frontpress#24]
É interessante ter botões de compartilhamento para detalhe de post, se for possível adiciona-los na listagem de post também seria bacana.

Talvez precise ser duas diretivas:
- Uma que compartilha a url atual;
- Uma que pode ser colocada dentro da lista de posts;

Possíveis parametrizações do componente (preferencialmente via model, mas talvez possa ser via diretiva):
- Quais redes em que o conteúdo vai ser compartilhado

**Comment by teles** [comment]
Material útil: https://willianjusten.com.br/share-button-sem-dependencias/

**Comment by alisonmonteiro** [comment]
@teles comecei a cria esta diretiva ontem. Assim que estiver ok, mando um PR. ;)

**Comment by teles** [comment]
Boaaa, monstro :D

**Comment by teles** [comment]
O PR do @alisonmonteiro resolveu o problema. Muito obrigado :D 
Mais para frente deveremos ter um problema relativo a compartilhamento, que é:
- Garantir que o facebook mostre um resumo correto para os posts dentro do contexto de SPA do frontpress

(Mais para frente pretendo recomendar o uso de prerender.io com o frontpress, aí pensamos novamente nisso)

Muito obrigado pela solução da issue!

**Comment by alisonmonteiro** [comment]
Massa, @teles! 😄 

> Garantir que o facebook mostre um resumo correto para os posts dentro do contexto de SPA do frontpress

Acho que isso, e, **talvez** o uso de cards do twitter poderiam entrar em uma nova issue.
Ex. de card: [aqui](https://twitter.com/TechCrunch/status/491955931719434241?ref_src=twsrc%5Etfw)

O que acha?
