### ISSUE TITLE
Definição de issues para próximo release

### ISSUE THREAD

**Issue by teles** [teles/frontpress#27]
Lancei um [release beta](https://github.com/teles/frontpress/releases/tag/v0.1-beta.1) do frontpress, e penso em definir as próximas entregas.

Conto com a opinião de quem estiver lendo isso para ajudar a definir a próxima entrega do frontpress.
1. SEO:
   1.1 - Suportar canonical
   1.2 - Suportar schema.org: article, schema de menu navegação, website e outros
2. Configurações no frontpress.json
   2.1 - Adicionar gulp prompt para gerar frontpress.json
   2.2 - Melhorar mensagem de erro quando frontpress.json não existe ainda no repositório
   2.3 - Configuração: infinite-scroll: false (para não usar infinite-scroll)
   2.4 - Configuração: favicon (informa endereço do favicon)
   2.5 - Configuração: removeCssClasses (remove classes css dos conteúdos retornados)
   2.6 - Configurações: filters.tags , filters.categories (filtra posts que irão aparecer no blog)
   2.7 - Configuração: overrides.useFirstImageAsFeatured: true (usa primeira imagem do post como featured image)
   2.8 - Configuração: html5Mode: false (permite que o site seja usado com html5Mode(false) )
3. Empacotando
   3.1 - Empacotar para ser usado no bower, acho que nesse caso só seriam úteis os componentes e não as views
   3.2 - Ver se faz sentido empacotar para o npm e como seria
   3.3 - Ver se faz sentido empacotar para o yeoman e como seria
4. Melhorias de desempenho
   4.1 - [Remover debug info](https://medium.com/swlh/improving-angular-performance-with-1-line-of-code-a1fb814a6476)
   4.2 - Analisar aplicação de one way data bind
   4.3 - Minificar javascript em um único arquivo
   4.4 - Dividir em 'gulp local' e 'gulp deploy' com javascript não minificado X minificado
   4.5 - Adicionar templateCache para servir os templates angular
   4.6 - Garantir que as chamadas a api do wordpress estejam retornando apenas campos necessáros
5. [Suporte a github pages](http://www.backalleycoder.com/2016/05/13/sghpa-the-single-page-app-hack-for-github-pages) cria redirecionamentos e usa 404.html para que frontpress possa ser usado com html5mode true no github pages
6. Verificar comportamento da paginação:
7. Ver como a paginação se comporta com navegação do usuário quando este clica em "voltar" do navegador
8. Adicionar suporte ao google analytics com angularitics 
9. Botões de compartilhar para maioria das redes sociais https://github.com/teles/frontpress/issues/24
10. Suporte a páginas (igual a posts) https://github.com/teles/frontpress/issues/17
11. Rodapé e cabeçalhos padrões
    10.1 - Adicionar rodapé padrão
    10.2 - Adicionar cabeçalho padrão
12. Exemplo do site funcionando com gh-pages (gerado via integração automática com travis https://github.com/teles/frontpress/issues/6 )
13. Criar as principais diretivas do sistemas de tags auxiliares https://github.com/teles/frontpress/issues/23
14. Qualidade de software
    13.1 - Implementar suite básica de testes unitários
    13.2 - Adicionar jshint para o código
    13.3 - Criar mocks para possibilitar testes unitários
    13.4 - Adicionar githooks que validam js e html
15. Novas páginas
    14.1 - Páginas de categorias
    14.2 - Páginas de tags
    14.3 - Página de previsualização de post sendo editado

cc @woliveiras @alisonmonteiro @dineshTrivedi 

Preciso definir as coisas para uma próxima versão do frontpress. O que voce acha importante?

**Comment by woliveiras** [comment]
Caramba! Completasso!

**Comment by teles** [comment]
Lembrei de mais coisas para o item 2:

2.9 - Configuração: postPath (configura url do detalhe de post, valor ex: "/:category/:slug"
2.10 - Configuração: paginatePath (configura url da paginacao, valor ex: '/pagina/:pageNumber' )

**Comment by teles** [comment]
Tem mais:

16 - Widget de posts relacionados

**Comment by teles** [comment]
Vou fechar o release [beta-2](https://github.com/teles/frontpress/milestone/3) com as seguintes entregas programadas:

1.2. Suportar schema.org: article, schema de menu navegação, website e outros
4.1 - Remover debug info
4.3 - Minificar javascript em um único arquivo
4.4 - Dividir em 'gulp local' e 'gulp deploy' com javascript não minificado X minificado
4.5 - Adicionar templateCache para servir os templates angular
6. Verificar comportamento da paginação:
9. Botões de compartilhar para maioria das redes sociais
10. Suporte a páginas (igual a posts)
