### ISSUE TITLE
Adicionar prompt para configuração do frontpress.json

### ISSUE THREAD

**Issue by teles** [teles/frontpress#29]
Adicionar um prompt ao gulp para configuração do frontpress.json.

Essa é uma das coisas planejadas na issue #27.

**Comment by teles** [comment]
Uma boa ideia aqui é adicionar um comportamento de ao rodar `gulp` é verificado se frontpress.json já existe, senão existir roda-se o `gulp init` antes dos outros comandos.

**Comment by teles** [comment]
@woliveiras se quiser, fica a vontade para terminar essa issue. O que falta:
- Quando a task default rodar, ele deve verificar se existe o frontpress.json, senão existir roda o init antes das outras tasks todas.

**Comment by woliveiras** [comment]
Pra ontem!

**Comment by teles** [comment]
Está muito tenso conseguir fazer uma task que rode primeiro `gulp init`, gera o frontpress.json e em seguida rode `gulp`. 
Então vou dar essa issue por encerrada e sugerir no readme que usuários rodem:

`gulp init`
`gulp`
