### ISSUE TITLE
Minificação de javascript em um único arquivo

### ISSUE THREAD

**Issue by teles** [teles/frontpress#32]
Minificar o javascript em um único arquivo que deverá ser enviado para eventuais deploys.
Garantir que exista uma task

```
gulp
```

que minifica o arquivo, e outra:

```
gulp dev
```

que não minifica.

Ou alguma outra estrutura que pareça fazer sentido.

**Comment by alisonmonteiro** [comment]
@teles uma sugestão que fica aqui é uma que eu utilizei bastante. Caso goste:

`gulp`: Não minifica os arquivos
`gulp --production` ou, apenas `gulp production` : Minifica, preparando tudo pros eventuais deploys

👍

**Comment by teles** [comment]
Excelente ideia, @alisonmonteiro. Acho válido ser feito assim :D

**Comment by alisonmonteiro** [comment]
@teles estou trabalhando nesta issue. Assim que possível mando um PR. 😄

**Comment by teles** [comment]
Acha que faria sentido que os arquivos external e app fossem minificados em apenas um arquivo, @alisonmonteiro ?

**Comment by alisonmonteiro** [comment]
Acho sim, @teles 
Vou trabalhar nisso hoje! Assim q estiver pronto, eu atualizo.

**Comment by teles** [comment]
Beleza, @alisonmonteiro
Eu também to mexendo no repositório esses dias. Valeu, :D 

Acho que o próximo release já vai tornar o frontpress usável para quem tem a versão 2 da api do wordpress.

**Comment by alisonmonteiro** [comment]
Show, @teles 
Ainda n mandei a atualização, estou buscando uma forma que fique mais arrumada, sabe?
Assim que estiver ok, te mando.

**Comment by teles** [comment]
Beleza pura @alisonmonteiro :D

**Comment by teles** [comment]
Vou esperar você terminar essa issue para fazer outra de templateCache do frontpress, @alisonmonteiro  :D

**Comment by alisonmonteiro** [comment]
@teles foi mal pelo delay, mano. Estava viajando e só estou de volta agora. Estou finalizando esta atividade. :)

**Comment by teles** [comment]
Valeu, @alisonmonteiro  :D 
Vou ver o PR até terça feira.

**Comment by teles** [comment]
@alisonmonteiro muito obrigado mesmo. Está excelente. Fechando a issue.
