### ISSUE TITLE
Generalizar a `parseConfigsToParams` para toda a API

### ISSUE THREAD

**Issue by alisonmonteiro** [teles/frontpress#45]
@teles 
A funcão `parseConfigsToParams`, que é bem simples, está se repetindo em quatro locais diferentes. Dentro da pasta `apis/`, em `categories, medias, posts e tags`. 

[Link para a função completa](https://github.com/teles/frontpress/blob/master/src/js/apis/categories/models/categories-api.model.js#L15-L25).

Acha que podemos generalizar ela? Posso pegar isso. Pensei em criar um arquivo ou pasta dentro de `apis/` para funções deste estilo. O que acha?

Vlw!

**Comment by teles** [comment]
Uhum, boa @alisonmonteiro . Eu já pensei em fazer isso uma vez mas esquecí, pode pegar para fazer dentro da pasta api como achar melhor :)
