### ISSUE TITLE
Criar suite de testes inicial

### ISSUE THREAD

**Issue by taciogt** [teles/frontpress#52]
O fato de precisar dar suporte para duas versões diferentes da api do wordpress deixa o sistema muito sensível, o que aumenta a necessidade de testes para manter a confiabilidade do projeto. Essa issue é para criar um teste inicial, apenas para servir de exemplo para iniciar a cobertura de testes do projeto.
O entregável dessa issue pode ser uma task que roda um teste e gera um relatório de cobertura, mesma que o relatório diga que a cobertura é de 0%.

**Comment by taciogt** [comment]
@teles pode colocar essa issue no projeto de qualidade de código?

**Comment by teles** [comment]
Vou colocar, @taciogt . Valeu por criar a issue e pelo critério de pronto dela estar bem definido.

**Comment by teles** [comment]
Moví essa issue para "Desenvolvendo" no projeto de qualidade de código, @taciogt .

**Comment by taciogt** [comment]
@teles consegue me colocar como assignee desta issue?

**Comment by teles** [comment]
Feito, @taciogt

**Comment by teles** [comment]
@taciogt  os arquivos de teste (*_/_.test.js) estavam sendo concatenados juntos aos arquivos de produção.
Tirei os arquivos de teste do arquivo js de produção, beleza?

**Comment by taciogt** [comment]
@teles nem lembrei disso, valeu 👍
