### ISSUE TITLE
Estruturar um readme decentemente

### ISSUE THREAD

**Issue by teles** [teles/frontpress#53]
Pensei em criar um readme melhor que o atual. O readme atual dificultou a vida do @taciogt ao tentar rodar o projeto.

Esse readme precisa ter (**critério de pronto**):
- [x] Descrição curta sobre o que é o projeto
- [x] O que fazer da primeira vez que você rodar o frontpress.
- [x] O que fazer para rodar o frontpress em seguida;
- [x] Badge do gitter
- [x] Badge de qualidade do codacy

Esse readme seria mais legal se tivesse (**critério de ótimo**):
- [ ] Um logotipo
- [ ] Uma imagem para cada seção (talvez usar isso: https://asciinema.org)
- [ ] Uma imagem da licença do frontpress

Inspirações e orientações para criar esse readme: 
- https://github.com/noffle/art-of-readme
- https://github.com/matiassingers/awesome-readme

cc @alisonmonteiro 
## 

Esse comentário foi editado para incluir uma lista de checkpoints que sirva de critério de pronto. Sugestão do @alisonmonteiro

**Comment by teles** [comment]
Acho que não faz sentido adicionar essa issue no [projeto de qualidade de código](https://github.com/teles/frontpress/projects/2), certo?

**Comment by teles** [comment]
Se for fazer um logo as inspirações são:
- Logo do angular https://avatars0.githubusercontent.com/u/139426?v=3&s=400
- Logos de front: http://wicrew.com/wp-content/uploads/2015/07/html-css-js.png
- Logo do wordpress: https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/WordPress_logo.svg/2000px-WordPress_logo.svg.png

**Comment by taciogt** [comment]
@teles, acho que melhorar readme e contributing são melhorias da qualidade do código.

**Comment by teles** [comment]
Fechou. Adicionei essa issue ao projeto de qualidade de código, @taciogt.

**Comment by alisonmonteiro** [comment]
Massa, @teles!

Acho muito interessante a ideia. 
Acho válido manter o readme.md em inglês. Assim, ele alcança mais pessoas. O que acha?

Talvez, nós possamos deixar uma documentação mais elaborada no gh-pages, e no readme.md deixar apenas o essencial - com logo, descrição, comandos básicos (podemos manter em uma imagem), etc. 
Daí, no gh-pages, poderíamos usar algo como [typed-js](http://www.mattboldt.com/demos/typed-js/) ou o asciinema, como você citou.

Sobre o logotipo: acho que poderíamos ter uma issue com uma tag `help wanted` pra isso, assim quem manjar e quiser contribuir, ajudará bastante (infelizmente, não manjo de design 💩 ).

Um roadmap no readme.md: acho que não é tão necessário, já que temos os projetos e o milestone no github, mas para ficar mais claro, pode ser uma boa.

E concordo com o @taciogt. readme e contributing são melhorias da qualidade de código.

😄

**Comment by teles** [comment]
Valeu, @alisonmonteiro.

Acho muito válido ter o readme em inglês e colocar help wanted para o logo.
Até podemos pensar em gerar um concurso no openclipart.org para isso.

**Comment by teles** [comment]
O @woliveiras quer ajudar nisso :D

**Comment by woliveiras** [comment]
Opa!

Vou tentar ajudar a ajeitar um README legal! \o/

Achei muito boa a ideia de abrir um concurso ein?

**Comment by alisonmonteiro** [comment]
@teles podemos criar uma checklist (nesta issue mesmo) com os tópicos acima e ir marcando quando concluirmos algo. O que acha?

**Comment by teles** [comment]
@alisonmonteiro acho uma boa ideia, coloquei lá no primeiro comentário uma checklist :)

**Comment by alisonmonteiro** [comment]
@teles show! 😃 
Acho que algumas dessas já podemos marcar como concluídas. Me corrija, caso eu esteja enganado:
1. Descrição curta sobre o que é o projeto
2. O que fazer da primeira vez que você rodar o frontpress.
3. O que fazer para rodar o frontpress em seguida;
4. Badge do gitter
5. Badge de qualidade do codacy

**Comment by teles** [comment]
@alisonmonteiro levando em conta que já tem [outra issue para o contributing do frontpress](https://github.com/teles/frontpress/issues/54) removí o item sobre o contributing dessa issue.

Duas coisas que poderiam ser legais no readme em um futuro próximo:
- Tabela de suporte de navegadores
- Uma lista de links mais úteis da wiki do projeto

Agora vou considerar essa issue fechada pelo @alisonmonteiro! 
Novamente muito obrigado!

**Comment by alisonmonteiro** [comment]
@teles massa! 😄 

Sobre a logo, lembro que havíamos falado sobre... Iremos manter aquela ideia do concurso?
Acha que podemos abrir uma issue aqui com a tag `help wanted` também?
Até que curti as duas logos daquela forma no readme, mas uma própria do projeto seria muito melhor!

**Comment by teles** [comment]
Acho uma boa ideia, @alisonmonteiro. 
Como podemos criar essa issue bem especificada e chamar interessados em fazer o logo?

**Comment by teles** [comment]
Exemplos de logos de browser: https://github.com/alrra/browser-logos (também podemos usar isso depois para especificar o suporte do frontpress)

**Comment by rpaggi** [comment]
Pensei em algo assim, não sou designer mas to tentando ajudar:

![](http://i.imgur.com/42PS4v4.png)

**Comment by teles** [comment]
Legal, @rpaggi.
Pensei em criar algo que misture logos do angular, wordpress e css3/html5. Tipo o que você sugeriu.

**Comment by rpaggi** [comment]
Pelas suas sugestões foi isso mesmo que eu captei e tentei fazer. Só não conegui encaixar uma fonte legal ali

**Comment by khaosdoctor** [comment]
Acho que a própria fonte do CSS3 fica bacana ali, com um FP

**Comment by rpaggi** [comment]
Vocês tem o nome dessa fonte para eu procurar aqui?

**Comment by teles** [comment]
Valeu, @khaosdoctor e @rpaggi 

Criei uma nova issue com informações para criação do logo https://github.com/teles/frontpress/issues/70

**Comment by khaosdoctor** [comment]
Vou verificar lá e inicio algum esboço nessa semana

**Comment by alisonmonteiro** [comment]
@teles não havia respondido ainda, mas vi que você iniciou uma issue e tem bastante gente contribuindo. Muito massa! 😄
