### ISSUE TITLE
Criar um contributing relevante para o projeto

### ISSUE THREAD

**Issue by teles** [teles/frontpress#54]
Criar um contributing relevante para o projeto com informações a serem levadas em conta quando algum usuário desejar fazer um pull request para o projeto.

Passos:
- Ver exemplos de contributing bons;
- Definir quais informações são relevantes;
- Escrever em pt-br e/ou inglês

**Comment by alisonmonteiro** [comment]
@teles poderíamos adotar um padrão de mensagem para os commits. Sugiro o do próprio AngularJS. O que acha?

**Comment by teles** [comment]
Parece interessante, @alisonmonteiro .

To olhando os [commits do angular](https://github.com/angular/angular.js/commits/master) para ver se posso aprender como funciona.

Você tem algum link de documentação sobre o tema?

**Comment by alisonmonteiro** [comment]
Opa, @teles 

Tem sim! Aqui [o link](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit).

**Comment by teles** [comment]
[Lista de contributing bons](https://github.com/jonschlinkert/awesome-contributing)
