### ISSUE TITLE
Teste funcional do projeto de apis do wordpress

### ISSUE THREAD

**Issue by teles** [teles/frontpress#59]
O [projeto para consumir apis v1 e v2 do wordpress](https://github.com/teles/frontpress/projects/1) teve como finalidade resolver um problema apontado na issue #35. 

O wordpress sugere a depreciação da api v1, mas ainda a utiliza em todos os sites hospedados em wordpress.com. A api v2 é uma especificação utilizada desde 2013 como plugin criado pela própria equipe do wordpress.

**Resultado:** é necessário suportar no frontpress tanto a versão v1 quanto a v2 da api, apesar das diferenças gritantes entre elas.

---

Criei essa issue para servir de roteiro de teste do projeto das apis.
Sem mais delongas, o passo a passo para testar o funcionamento do frontpress para api v1 e v2 do wordpress é:
- [ ] Baixar e configurar o projeto do frontpress usando as [instruções do readme](https://github.com/teles/frontpress/blob/master/readme.md)
- [ ] Na raiz do projeto copiar o [arquivo de exemplo de configuração v1](https://github.com/teles/frontpress/blob/master/frontpress.json.v1.sample) e nomea-lo como `frontpress.json`
- [ ] Rodar o comando gulp
- [ ] Verificar a listagem de posts apenas garantindo que apresente: uma lista de posts com título, imagem de destaque, trecho, link funcionando
- [ ] Verificar um post completo garantindo que apresente: título, conteúdo do post, e ao final do post uma linha com **categorias** e outra linha logo abaixo com **tags do post**.

Basicamente repetir o mesmo processo para testar a v2.
- [ ] Parar o comando gulp
- [ ] Na raiz do projeto copiar o conteúdo do [arquivo de exemplo de configuração v2](https://github.com/teles/frontpress/blob/master/frontpress.json.v2.sample) e sobrescrever o conteúdo do `frontpress.json` com este conteúdo copiado
- [ ] Rodar o comando gulp
- [ ] Verificar a listagem de posts apenas garantindo que apresente: uma lista de posts com título, imagem de destaque, trecho, link funcionando
- [ ] Verificar um post completo garantindo que apresente: título, conteúdo do post, e ao final do post uma linha com **categorias** e outra linha logo abaixo com **tags do post**.

cc @taciogt

**Comment by teles** [comment]
Correções a serem feitas:

### No post completo versão v1 da api não aparece data do post :warning:

Todo o resto pareceu estar ok, incluindo data do post completo na v2.

**Comment by teles** [comment]
Corrigido problema levantado acima.

**Comment by teles** [comment]
@taciogt reportou um problema de erro 404 usando a api v1. Pode descrever melhor aqui, Tácio? :)

**Comment by taciogt** [comment]
Claro, @teles

Fiz o seguinte:
Mandei um `gulp init` com as seguintes configurações:
`wordpress rest api url: default`
`api version: v2`
`disqus: no`

Ao abrir o localhost:4000, ficou travado na mensagem "Carregando posts" e "Carregando posts novos" e o seguinte erro foi impresso no console do Chrome:
`GET https://public-api.wordpress.com/rest/v1.1/sites/en.blog.wordpress.com/wp/v2/posts/?_envelope&page=1 404 ()`

**Comment by teles** [comment]
Isso é muito estranho, @taciogt.
Parece que está sendo passada a configuração para ser usada a api v2, mas a url base do rest é de um wordpress v1.

Você pode trocar no `frontpress.json` a `"restApiUrl"` por `https://www.vivadecora.com.br/revista/wp-json` e ver se o erro persiste?

**Comment by teles** [comment]
Conversei com o @taciogt e ví que o que estava rolando aqui é: Depois de testar a api v1 o Tácio manteve no frontpress.json o valor do restApiUrl mas alterou manualmente o valor de apiVersion.

Disso eu concluí que:
1. É interessante mexer [na task init](https://github.com/teles/frontpress/blob/master/tasks/init.js) para dificultar que seja possível informar primeiro uma url de api v1 e depois setar apiVersion como v2 (ou vice-versa);
2. É interessante dar uma mensagem de erro no console quando a api passada não existir.

**Comment by teles** [comment]
Estou considerando essa issue fechada.
Testes foram feitos e sugestões de melhorias foram levantadas graças a esse teste.

Valeu, @taciogt !
