### ISSUE TITLE
Branch gh-pages funcional

### ISSUE THREAD

**Issue by teles** [teles/frontpress#6]
Subir uma branch gh-pages funcional, que exibe o resultado dos comandos:

`npm i && bower i && gulp`

Usar o travis para isso parece ser uma boa solução.

**Comment by alisonmonteiro** [comment]
@teles aqui você pensa em usar algo [assim](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd) ou algo mais manual?

Abs!

**Comment by teles** [comment]
@alisonmonteiro pensei em fazer automatizado mesmo, como no link que você mandou.

**Comment by teles** [comment]
Por enquanto fiz [esse projeto](http://jotateles.com.br/demo-frontpress/#!/) para servir de exemplo de uso do FrontPress, posteriormente farei novos exemplos.

Não pretendo mais usar a gh-pages deste repositório para finalidade de construir exemplos de uso do FrontPress. Motivos:

* Agora existe uma org em que novos repositórios podem ser criados apenas para exemplos;
* Código da master e da gh-pages ficaria muito diferente.
