### ISSUE TITLE
Melhorias na task init para evitar confusões entre versões de api

### ISSUE THREAD

**Issue by teles** [teles/frontpress#68]
Como visto após teste feito na #59. 

É necessário:
- [ ]  É interessante mexer na task init para dificultar que seja possível informar primeiro uma url de api v1 e depois setar apiVersion como v2 (ou vice-versa);
- [ ]  É interessante dar uma mensagem de erro no console quando a api passada não existir.

Ainda não sei a melhor forma de fazer isso.
Talvez dê para inferir a versão da api depois de passada a url ao invés de perguntar a versão para o usuário.

Basicamente, até onde sei, sites em wordpress.com usam api v1 e sites fora de wordpress.com usam api v2.

É bom levar em conta que futuramente novas apis (mesmo fora do contexto do wordpress) podem ser adicionadas ao projeto.

**Comment by alisonmonteiro** [comment]
@teles estava observando alguns detalhes e percebi que as APIs da versão 2 tem uma propriedade na sua "rota" principal.

``` json
"namespaces": [
  "wp/v2"
]
```

Acho que poderíamos usar este `wp/v2` como parâmetro, deixando bem estruturado para que em futuras APIs seja mais fácil de adicionar uma nova "regra", caso necessário.

O que acha?

**Comment by teles** [comment]
@alisonmonteiro achei uma boa ideia seu comentário acima.
Essa issue ficaria melhor no projeto frontpress-cli, ne?
