### ISSUE TITLE
Criar logo para projeto FrontPress

### ISSUE THREAD

**Issue by teles** [teles/frontpress#70]
É interessante criar um logo para o FrontPress, para ajudar a divulga-lo já que ele deve ter uma versão estável para utilização no final desse ano. 

### O que é o FrontPress?

FrontPress é um projeto open source de um site completo compatível com as principais apis do WordPress. Não é um tema WordPress, é uma aplicação frontend completa e customizável.

### Público alvo

* Desenvolvedores front-end que precisam/querem trabalhar com WordPress;
* Desenvolvedores que gostam de testar tecnologias novas;
* Desenvolvedores que querem aprender como criar um site completo usando angular.

### Serviço prestado

* Um template front-end customizável e extensível capaz de utilizar as APIs do WordPress;
* Uma solução que concilia a utilização do dashboard do WordPress sem a necessidade de utilização de um tema WordPress;
* Uma SPA completa compatível com API WordPress.

### Premissas para identidade visual

* Cores: ainda não definidas;
* Nome do projeto: FrontPress.

Seria interessante ser algo que lembrasse projetos/tecnologias relacionadas como:

* Angular
* CSS3 / HTML5 / PHP7 (não é utilizado, mas parece com os outros citados)
* WordPress

Ideias: 
* Fazer uma letra F que se pareça com um ⚡️  (pode ser muito óbvio)
* Fazer uma letra F que pareça algo em construção (deixando claro que é customizável)

cc @alisonmonteiro @woliveiras 

### Critério de pronto dessa issue:

T̶e̶r̶ ̶p̶e̶l̶o̶ ̶m̶e̶n̶o̶s̶ ̶5̶ ̶l̶o̶g̶o̶s̶ ̶v̶á̶l̶i̶d̶o̶s̶ ̶p̶a̶r̶a̶ ̶a̶b̶r̶i̶r̶ ̶v̶o̶t̶a̶ç̶ã̶o̶.̶

EDITADO:

Alterei critério de pronto: Votação começa com logos que estiverem prontos em 05/12 (segunda).

**Comment by rpaggi** [comment]
Minha opção: 
![Logo](http://i.imgur.com/2Tp8ZTe.png)

**Comment by frrrnd** [comment]
Baseado nas outras de html/css etc... Minha opção:

![front-press](https://cloud.githubusercontent.com/assets/2320940/19895534/444ba71c-a038-11e6-8e83-c7544d4a5d83.png)

**Comment by teles** [comment]
Inspirações:

![](https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Gatorade_logo.svg/1280px-Gatorade_logo.svg.png) 
![](https://s-media-cache-ak0.pinimg.com/564x/43/bb/10/43bb10878e8f75318c2ffaceb3a3876d.jpg)
![](http://www.beacontechnologies.com/blog/wp-content/uploads/2013/09/html5-css3-rwd-300x136.png)
![](http://angularconnect.com/workspace/2015/img/resources/angular.png)
![](https://s.w.org/about/images/logos/wordpress-logo-stacked-rgb.png)
![](https://s-media-cache-ak0.pinimg.com/236x/44/dd/2b/44dd2b8d7717d66aff1a8f8f245f9481.jpg)

**Comment by teles** [comment]
![Logo do instant articles](http://65.media.tumblr.com/3509628cc9b656d8cb7e305c0f0e9b51/tumblr_inline_o361ekbOjx1qa90wi_500.png)
![Logo do AMP](http://www.greenmellenmedia.com/wp-content/uploads/amp-project.jpg)

**Comment by mppagano** [comment]
<img src="http://i.imgur.com/NMojAjq.png" />

**Comment by mppagano** [comment]
<img src="http://i.imgur.com/CUzRV17.png" />

**Comment by teles** [comment]
Curtí bem as opções do @mppagano 

Não sei se outras pessoas se incomodam também com a semelhança com o logo do Baidu. O que acham?
![](http://www.techspot.com/images2/downloads/topdownload/2014/11/BaiduAntivirus.png)

**Comment by AdrianoKuik1** [comment]
![logo-fp](https://cloud.githubusercontent.com/assets/4563634/19937877/0fb7df52-a10a-11e6-944d-0bb641ef2976.png)

**Comment by alisonmonteiro** [comment]
@AdrianoKuik1 boa! curti bastante.

**Comment by vicainelli** [comment]
E que tal usar o Wapuu??
Poderia substituir essa bola azul com o logo do WordPress por uma vermelha com o "A" do AngularJS.

![https://ja.wordpress.org/files/2011/09/wapuu.png](https://ja.wordpress.org/files/2011/09/wapuu.png)

**Comment by woliveiras** [comment]
Lokura! Que bixo é esse @vicainelli? 😂 

Não conhecia.

**Comment by vicainelli** [comment]
@woliveiras é um mascote que a comunidade do WP usa em vários lugares, até usaram no último [WordCamp Fortaleza](https://fortaleza.wordcamp.org/2016/), não sei muito da história e tal, mas é uma ideia...

![https://fortaleza.wordcamp.org/2016/files/2016/06/WordpressFortaleza-medium.png](https://fortaleza.wordcamp.org/2016/files/2016/06/WordpressFortaleza-medium.png)

**Comment by woliveiras** [comment]
Da hora!

**Comment by teles** [comment]
Que legal esse [Wappu](https://wapuu.jp/) :D 
Até mesmo as [versões que não ganharam para mascote da comunidade japonesa de wordpress](https://wapuu.jp/2015/12/12/wapuu-origins/) são legais e uma boa inspiração. no mínimo.

Obrigado pela dica, @vicainelli !

**Comment by teles** [comment]
![frontpress svg](https://cloud.githubusercontent.com/assets/762639/20249933/c8e343b0-a9eb-11e6-8c58-5b9a4b5967d6.png)

Só um exemplo de como poderia ficar minha ideia inicial. Meio bosta, né?

**Comment by woliveiras** [comment]
Eu achei da hora

**Comment by woliveiras** [comment]
Eu achei da hora

**Comment by teles** [comment]
1) F quadrado azul
![dino-azul](https://cloud.githubusercontent.com/assets/762639/20531450/f6d08598-b0bd-11e6-91b7-ca3e438d4536.png)

2) F quadrado vermelho
![dino-vermelho](https://cloud.githubusercontent.com/assets/762639/20531451/f6e9a12c-b0bd-11e6-8360-a8a882f0669d.png)

3) Asas azul
![latam-azul](https://cloud.githubusercontent.com/assets/762639/20531455/fd00a844-b0bd-11e6-9656-05ef31439272.png)

4) Asas vermelho
![latam-vermelho](https://cloud.githubusercontent.com/assets/762639/20531454/fd004d4a-b0bd-11e6-80e1-55faf2911217.png)


O que acham desses?

**Comment by woliveiras** [comment]
Invocando @baltazarparra e @ogilvieira

Conseguem ajudar?

**Comment by baltazarparra** [comment]
Opa! Vou ler o briefing e desenhar um conceito a noite.

**Comment by teles** [comment]
Estou pensando que para o FrontPress talvez seja mais importante passar a ideia de confiança e robustez do que de agilidade.

Motivo: como ele vai ser usado como base para projetos de outros usuários, o principal é ele ser confiável.

**Comment by baltazarparra** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/7395304/20582480/9c84ea78-b1c8-11e6-9a07-c629f0f9bc52.png)

**Comment by teles** [comment]
Valeu, @baltazarparra !
Curtí os símbolos!

**Comment by baltazarparra** [comment]
Que bom, são conceitos, podem ser aproveitados em outras ideias também, fiquem a vontade.

**Comment by teles** [comment]
Por hora vou considerar o logo mais curtido dessa issue como logo do FrontPress:

![](https://cloud.githubusercontent.com/assets/4563634/19937877/0fb7df52-a10a-11e6-944d-0bb641ef2976.png)

obrigado @AdrianoKuik1

**Comment by teles** [comment]
I am waiting @AdrianoKuik1 to update this organization image with his logo.

**Comment by woliveiras** [comment]
Please @AdrianoKuik1 

Pleeeease
