### ISSUE TITLE
Listar sites para divulgação do projeto FrontPress

### ISSUE THREAD

**Issue by teles** [teles/frontpress#75]
Com o lançamento da tag v0.1-beta2 pretende-se que o projeto já esteja estável o suficiente para ser usado por terceiros.

Quando isso ocorrer é interessante saber onde o projeto pode ser divulgado na própria internet gratuitamente.

Esses sites podem ser em português ou inglês.

### Critério de pronto dessa issue:

Pelo menos 10 sites listados para divulgação do projeto.
No entanto pensei em deixar a issue aberta e fechá-la somente no dia da primeira diulgação.

**Comment by teles** [comment]
O que vem na minha cabeça de imediato:
- Maquinário
- Product Hunt
- Blog jotateles.com.br
- Tableless
- BrazilJS Weekly
- Reddit Awesome Github
- Projetos awesome javascript no github
- Projetos awesome baas no github
- Tentar divulgar no smashing magazine (naquele post com coletânea de links)

**Comment by teles** [comment]
Se a documentação estiver boa, posso tentar incluí-la aqui: https://github.com/GitbookIO/gitbook/blob/master/docs/examples.md

**Comment by teles** [comment]
Também dá para tentar inclui-lo nesse cdn https://cdnjs.com/

**Comment by teles** [comment]
Acho que o FrontPress pode ser bem vindo também no site do @woliveiras  e no projeto FRONT ABC.

**Comment by teles** [comment]
Mais um site http://ngmodules.org/

**Comment by woliveiras** [comment]
@teles, na BrazilJS Weekly já foi.

Não usamos WordPress em nada das comunidades aqui do ABC pra forçar nosso pessoal a se familiarizar com o Git e GitHub, mano. - Se não vai por bem, aprenderemos a força! kkkk
