### ISSUE TITLE
Remover diretório media por conter apenas imagens que aparecem no readme

### ISSUE THREAD

**Issue by teles** [teles/frontpress#77]
Pensei em remover o [diretório media](https://github.com/teles/frontpress/tree/master/media) pois:

* Ele contém apenas dois arquivos não usados no código;
* Esses dois arquivos são imagens que não serão mais usadas quando tivermos um logo (ver #70)
* Essas duas imagens podem ser substituídas paliativamente por outras imagens [deste repositório](https://github.com/gilbarbara/logos/)

O que acha , @alisonmonteiro ?

**Comment by alisonmonteiro** [comment]
@teles vi que já fechou, mas acho 100% válida a ideia.

No futuro, você pensa em voltar este diretório ou hospedar a imagem em outro serviço? :)

**Comment by teles** [comment]
Eu estava pensando em colocar o logo inline como svg ou png com base64 no readme, mas ainda não pesquisei para saber se isso é possível.

O que acha?

Desculpe fechar a issue antes de ler sua resposta, caso você tivesse motivos eu desfaria o commit :)

Obrigado

**Comment by alisonmonteiro** [comment]
@teles sem problemas, relaxa. :)

Com svg eu já usei, e dá sim. Mas dependendo da estrutura do vetor, pode ficar um código meio grande. Vamos aguardar a logo chegar, e daí vemos. 😄 

Vou dar uma olhada sobre o base64. Eu acho que dá certo, mas vou me certificar.

Vlw!
