### ISSUE TITLE
Utilizar arquivo único de javascript após o build

### ISSUE THREAD

**Issue by alisonmonteiro** [teles/frontpress#9]
@teles 
Você acha que seria interessante utilizarmos uma [taks do gulp com o gulp-concat](https://www.npmjs.com/package/gulp-concat) para concatenar todos os arquivos em um só após o build? Ou talvez dois. Um `app.js` e um `external.js`, por exemplo.
Isso evitaria [auto]-chamar uma função anônima por arquivo.

Se precisar de ajuda em algo, me avisa! ;)

Vlw!

**Comment by teles** [comment]
Com certeza seria muito bom, @alisonmonteiro !
Inclusive pretendo usar o que você sugeriu mais o templateCache do angular.
Essa issue é muito válida.

**Comment by teles** [comment]
Fechado com o PR #12
