### ISSUE TITLE
Gerar arquivos de build do FrontPress e commitá-los no repositório 

### ISSUE THREAD

**Issue by teles** [teles/frontpress#93]
É necessário que seja possível usar o FrontPress sem a necessidade de uma cli.
Assim deve ser possível utilizar o FrontPress como uma lib importável em seu próprio projeto.

Para isso é necessário oferecer para o usuário arquivos "pre-buildados" do FrontPress em uma pasta com nome `build`: 

* Um arquivo `frontpress.min.js` que contém todos os js de: [api v2](https://github.com/teles/frontpress/tree/master/src/js/apis/v2), [components](https://github.com/teles/frontpress/tree/master/src/js/components), [filters](https://github.com/teles/frontpress/tree/master/src/js/components), [views](https://github.com/teles/frontpress/tree/master/src/js/components), [frontpress.config.js](https://github.com/teles/frontpress/blob/master/src/js/frontpress.config.js), [frontpress.js](https://github.com/teles/frontpress/blob/master/src/js/frontpress.js) (que precisa ter nome alterado para frontpress.module.js), [frontpress.run.js](https://github.com/teles/frontpress/blob/master/src/js/frontpress.run.js), arquivo de template-cache.

* Um arquivo `frontpress.v1.min.js` que contém todos os js de: [api v1](https://github.com/teles/frontpress/tree/master/src/js/apis/v1), [components](https://github.com/teles/frontpress/tree/master/src/js/components), [filters](https://github.com/teles/frontpress/tree/master/src/js/components), [views](https://github.com/teles/frontpress/tree/master/src/js/components), [frontpress.config.js](https://github.com/teles/frontpress/blob/master/src/js/frontpress.config.js), [frontpress.js](https://github.com/teles/frontpress/blob/master/src/js/frontpress.js) (que precisa ter nome alterado para frontpress.module.js), [frontpress.run.js](https://github.com/teles/frontpress/blob/master/src/js/frontpress.run.js), arquivo de template-cache.

O [frontpress.controller.js](https://github.com/teles/frontpress/blob/master/src/js/frontpress.controller.js) não é necessário por se tratar de um arquivo que só existe por conta do index.html.

## Observações importantes e requisitos:
* É interessante que esses arquivos sejam gerados via travis a cada deploy (garantindo sua atualização, minimizando chance de arquivo gerado incorretamente)
* Hoje já é gerado e [ignorado](https://github.com/teles/frontpress/blob/master/.gitignore) um diretório chamado `build`, é necessário trocar o nome desse diretório para que o novo diretório `build` possa ser usado.
* Já tem task no gulp que gera um arquivo chamado main.js, a estrutura do main.js é muito parecida com a estrutura esperada para os arquivos acima citados.

**Comment by teles** [comment]
@iuryalves caso queira posso te explicar qual é a ideia aqui.

**Comment by IuryAlves** [comment]
@teles  Blz.

**Comment by teles** [comment]
Os arquivos estão sendo gerados pela task `gulp release` (contribuição do @IuryAlves ) e sendo commitados no repositório. Agora falta:

* [x] - No script de deploy quando nenhum dos arquivos gerados (`frontpress.min.js`, `frontpress.v1.min.js`) não forem alterados **não fazer um push pelo Travis CI**.
* [x] - Aparentemente os arquivos `frontpress.min.js` e `frontpress.v1.min.js` estão iguais - é necessário verificar se o conteúdo deles está correto;
* [ ] - Depois de corrigidos os arquivos fazer um exemplo de app importando os arquivos.

**Comment by teles** [comment]
Depois de bater a cabeça um pouco resolví a issue.

O que acontecia: na minha máquina ao rodar `gulp release` após alterar um .js os arquivos de release eram regerados. No Travis isso não acontecia, ele dizia que após o `gulp release` o repositório continuava igual.

Aí descobrí que meu `gulp release` local que estava errado, pois ele não estava importando a maioria dos meus js, apenas os arquivos de dependências, que jamais eram alterados.

Alterei a task de release e agora os arquivos são gerados corretamente.

**Problema:** quando os arquivos são minificados eles estão deixando de funcionar, provavelmente por conta da injeção de dependências do angular. Para resolver isso criarei outra issue.

**Comment by IuryAlves** [comment]
Fecha a issue então. Cuzão.

@teles

**Comment by teles** [comment]
@IuryAlves suas doces palavras tocaram meu coração. Fechando a issue, valeu pela ajuda.
