### ISSUE TITLE
Criar função de configuração do projeto o $FrontPressProvider

### ISSUE THREAD

**Issue by teles** [teles/frontpress#97]
O FrontPress deverá poder ser usado opcionalmente sem uma [cli](https://github.com/frontpressorg/frontpress-cli).

É com a utilização da cli que o [arquivo de configuração frontpress.json se torna uma constant angular](https://github.com/frontpressorg/frontpress/blob/master/tasks/ngConfig.js).

Esse processo que utilizada o frontpress.json ocorre com a chamada da função `$FrontPressProvider.configure.load()`.

Essa issue deve permitir que o $FrontPressProvider possa ser opcionalmente configurado através de um objeto javascript sem a utilização do frontpress.json. Algo como:

```javascript
var module = angular.module("my-wonderful-blog");

function MyConfig($FrontPressProvider){
    var configuration = {
	"restApiUrl": "https://demo.wp-api.org/wp-json",
	"apiVersion": "v2",
	"pageSize": 5,
	"infiniteScroll": true,
	"routes": {
		"post": "/:postYear/:postMonth/:postDay/:postSlug",
		"home.pagination": "/pagina/:pageNumber"
	},
	"titles": {
		"post": ":postTitle - :siteName",
		"home": "Home - :siteName"
	},
	"overrides": {
		"siteName": "FrontPress Default Template"
	}
   };

    $FrontPressProvider.configure.set(configuration);    
}

module.config(MyConfig);
```

O resultado dessa issue somado ao resultado da issue #93 possibilitará a utilização do FrontPress como biblioteca importável em qualquer projeto.

**Comment by teles** [comment]
O problema aqui tem sido o seguinte:

* Durante o `.config` das rotas [home](https://github.com/frontpressorg/frontpress/blob/master/src/js/views/home/home.routes.js) e [post](https://github.com/frontpressorg/frontpress/blob/master/src/js/views/post/post.routes.js)  é necessário chamar a função `$FrontPressProvider.configure.loadRoutes();`

Essa função retorna as rotas configuradas para a home e o post, como se fosse um `get` para essa informações.

No entanto as rotas só são configuradas durante o [config  da aplicação principal que injeta o FrontPress](https://github.com/frontpressorg/frontpress/blob/master/src/js/sample-blog.config.js#L4).

Ocorre que a ordem para rodar os configs é:
* Roda o config das dependências - rotas da home e post;
* Roda o config da aplicação principal

Por isso caso eu tente rodar o `loadRoutes()` pegando valores que foram passados durante o config da aplicação principal os valores retornados são `null`;

**Comment by teles** [comment]
Hoje a função `FrontPressProvider.configure.loadRoutes();` funciona usando o arquivo frontpress.json porquê o arquivo frontpress.json gera um `FrontPressConfigurationFile` que já está disponível durante os configs das rotas.

**Comment by teles** [comment]
It's working now. 
Many thanks to @dineshtrivedi who helped me finding a good solution.

I was thinking about recreate `home.routes.js` and `post.routes.js`, but I decided to leave the decision of creating or not those files for the future :)

**Comment by dineshtrivedi** [comment]
It is a Pleasure, @teles :)
